# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [95]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [96]:
A = np.arange(1, 16).reshape(3,5)

In [97]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [98]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [99]:
print(B - C)
print()
print(B * C)
print()
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [100]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [101]:
#Exponentiate each number elementwise (use the np.exp function).
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [102]:
#Calculate the minimum value in the whole matrix.
B.min()

1

In [103]:
#Calculcate the minimum value in each row. 
B.min(axis=1)

array([1, 4, 7])

In [104]:
#Calculcate the minimum value in each column. 
B.min(axis=0)

array([1, 2, 3])

In [105]:
#Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
B.argmin()

0

In [106]:
#Find the index value for the minimum value in each row (hint: use np.argmin).
B.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [107]:
#Calculate the sum for all elements.
B.sum()


45

In [108]:
#Calculate the mean for each column.
B.mean(axis=0)

array([4., 5., 6.])

In [109]:
np.median(B, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [110]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [111]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [112]:
#The missing indices are considered complete slices

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [113]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [114]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [115]:
#you can use the flate attribute, see below for exampel

for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [116]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [117]:
# a has been reshaped by the reshape function from 1D - > 3D

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [118]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [119]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [120]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [121]:
import numpy as np

def add_mult_matrices(mat1, mat2, operation):
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        return "The matricies must be numpy.ndarray."
              
    if operation == 'add':
        if mat1.shape == mat2.shape:
            return mat1 + mat2
        else:
            return "The matricies must be same shape to be added"
    
    elif operation == 'multiply':
        if mat1.shape[1] == mat2.shape[0]:
            return mat1 @ mat2    
        else:
            return "The number of columns in the first matrix must be equal to the number of rows in the second matrix."
        

#example no match of matrices  
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8], [3, 4]])

result_add = add_mult_matrices(mat1, mat2, "add")
print("Addition result: ", result_add)
result_multiply = add_mult_matrices(mat1, mat2, "multiply")
print("Multiplication result: ", result_multiply)

Addition result:  The matricies must be same shape to be added
Multiplication result:  The number of columns in the first matrix must be equal to the number of rows in the second matrix.


In [122]:
#example match of matrices 
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

result_add = add_mult_matrices(mat1, mat2, "add")
print("Addition result: ", "\n",result_add)
result_multiply = add_mult_matrices(mat1, mat2, "multiply")
print("Multiplication result: ","\n", result_multiply)

Addition result:  
 [[ 6  8]
 [10 12]]
Multiplication result:  
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [123]:
#Since there are so many assignments, I wrote additional code to better describe the answers and avoid mixing them up
#10.1.1

task_one = np.array([4, 3])

#a
print("a:", "\n","Shape:",task_one.shape)
#b
print("b:", "\n",task_one * 5)
#c
print("c:", "\n",task_one * 3)
#d
print("d:", "\n",(task_one * 5) + (task_one * 3))
#e
print("e:", "\n",task_one * 8)
#f
print("f:", "\n", (task_one * 4) - task_one)
#g
task_one_reshape = task_one.reshape(2,1)
print("g:", "\n", task_one_reshape)
print("Shape:",task_one_reshape.shape)
#h
#Svar nej, vektorerna har olika dimensioner
#i
task_one_norm = np.linalg.norm(task_one)
print("i:", task_one_norm)

a: 
 Shape: (2,)
b: 
 [20 15]
c: 
 [12  9]
d: 
 [32 24]
e: 
 [32 24]
f: 
 [12  9]
g: 
 [[4]
 [3]]
Shape: (2, 1)
i: 5.0


In [124]:
#10.1.2

task_two = np.array([[3], [7], [0], [11]])

#a
print("a:", "\n","Shape:", task_two.shape)
#b
print("b:", "\n",task_two * 2)
#c
print("c:", "\n",(task_two * 5) + (task_two * 2))
#d
print("d:", "\n",(task_two * 4) - (task_two * 2))
#e
task_two_reshape = task_two.reshape(1, 4)
print("e:", "\n",task_two_reshape)
#f
task_two_norm = np.linalg.norm(task_two_reshape)
print("f:", "\n",task_two_norm)

a: 
 Shape: (4, 1)
b: 
 [[ 6]
 [14]
 [ 0]
 [22]]
c: 
 [[21]
 [49]
 [ 0]
 [77]]
d: 
 [[ 6]
 [14]
 [ 0]
 [22]]
e: 
 [[ 3  7  0 11]]
f: 
 13.379088160259652


In [125]:
#10.1.3

vector_one = np.array([4, 3, 1, 5])
vector_two = np.array([2, 3, 1, 1])

print("Shape:", vector_one.shape)
print("Shape:", vector_two.shape)

#a
norm_one = np.linalg.norm(vector_one)
print("a:", "\n",norm_one)

#b
new_vector = vector_one - vector_two
norm_new_vector = np.linalg.norm(new_vector)
print("b:", "\n",norm_new_vector)

Shape: (4,)
Shape: (4,)
a: 
 7.14142842854285
b: 
 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [126]:
#I updated the add_mult_matrices function to work with subtraction too and chose to write a new one to keep the code togheter.

import numpy as np

def add_sub_mult(a, b, operation):
    if not isinstance(a, np.ndarray) or not isinstance(b, np.ndarray):
        return "The matricies must be numpy.array."
        
    
    if operation == 'add':
        if a.shape == b.shape:
            return a + b
        else:
            return "The matricies must be same shape, not defined"
            
    elif operation == 'sub':
        if a.shape == b.shape:
            return a - b
        else:
            return "The matricies must be same shape, not defined"
    
    elif operation == 'multiply':
        if a.shape[1] == b.shape[0]:
            return a @ b
        else:
            return "The number of columns in the first matrix must be equal to the number of rows in the second matrix, not defined"

a = np.array([[1], [2]])
b = np.array([[1], [2]])

result_add = add_sub_mult(a, b, "add")
result_sub = add_sub_mult(a, b, "sub")
result_multiply = add_sub_mult(a, b, "multiply")


In [135]:
A = np.array([[2, 1, -1],[1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])


In [128]:
#10.2.1 a - f

#a
print("Answer a: ", "\n", A * 2) 
print()
#b
a = B
b = 2 * A
result_b = add_sub_mult(a, b, "sub")
print("Answer b: " , "\n", result_b)
print()
#c
a = 3 * C
b = 2 * E
result_c = add_sub_mult(a, b, "sub")
print("Answer c: " , "\n", result_c)
print()
#d
a = 2 * D
b = 3 * C
result_d = add_sub_mult(a, b, "sub")
print("Answer d: ", "\n", result_d)
print()
#e
D_trans = D.T
a = D_trans
b = 2 * D
result_e = add_sub_mult(a, b, "add")
print("Answer e: ", "\n", result_e)
print()
#f
C_trans = C.T
a = 2 * C_trans
b = 2 * D_trans
result_f = add_sub_mult(a, b, "sub")
print("Answer f: ", "\n", result_f)
print()

Answer a:  
 [[ 4  2 -2]
 [ 2 -2  2]]

Answer b:  
 [[ 0 -4  3]
 [ 0 -2 -4]]

Answer c:  
 The matricies must be same shape, not defined

Answer d:  
 [[3 2]
 [2 3]]

Answer e:  
 [[ 9 12]
 [12  9]]

Answer f:  
 [[-4 -4]
 [-4 -4]]



In [129]:
#10.2.1 g - l

#g
A_trans = A.T
a = A_trans
b = B
result_g= add_sub_mult(a, b, "sub")
print("Answer g: ", "\n", result_g)
print()
#h
a = A
b = C
result_h= add_sub_mult(a, b, "multiply")
print("Answer h: ", "\n", result_h)
print()
#i
a = C
b = D
result_i= add_sub_mult(a, b, "multiply")
print("Answer i: ", "\n", result_i)
print()
#j
a = C
b = B
result_j= add_sub_mult(a, b, "multiply")
print("Answer j: ", "\n", result_j)
print()
#k
a = C
b = I
result_k= add_sub_mult(a, b, "multiply")
print("Answer k: ", "\n", result_k)
print()
#l
B_trans = B.T
a = A
b = B_trans
result_l= add_sub_mult(a, b, "multiply")
print("Answer l: ", "\n", result_l)

Answer g:  
 The matricies must be same shape, not defined

Answer h:  
 The number of columns in the first matrix must be equal to the number of rows in the second matrix, not defined

Answer i:  
 [[11 10]
 [10 11]]

Answer j:  
 [[  8 -10  -3]
 [ 10  -8   0]]

Answer k:  
 [[1 2]
 [2 1]]

Answer l:  
 [[5 2]
 [7 4]]


In [130]:
#10.2.2

matrix = np.array([[2, 3, 4],[5, 4, 1]])
matrix_trans = matrix.T
print(matrix)
print(matrix_trans)

a = matrix
b = matrix_trans

result_matrix = add_sub_mult(a, b, "multiply")
print(result_matrix)

[[2 3 4]
 [5 4 1]]
[[2 5]
 [3 4]
 [4 1]]
[[29 26]
 [26 42]]


In [131]:
#10.2.3
mat_A = np.array([[1, 2],[2, 4]]) 
mat_B = np.array([[2, 1],[1,3]])
mat_C = np.array([[4, 3],[0, 2]])

a = mat_A
b = mat_B
result_AB = add_sub_mult(a, b, "multiply")
print("AB", "\n", result_AB)
print()

a = mat_A
b = mat_C
result_AC = add_sub_mult(a, b, "multiply")
print("AC", "\n", result_AC)
print()

print("B", "\n", mat_B)
print("C", "\n", mat_C)

AB 
 [[ 4  7]
 [ 8 14]]

AC 
 [[ 4  7]
 [ 8 14]]

B 
 [[2 1]
 [1 3]]
C 
 [[4 3]
 [0 2]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [132]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [133]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [134]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
